services:
  - type: web
    name: carbontrack
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: SECRET_KEY
        value: your_very_secret_key
      - key: SECURITY_PASSWORD_SALT
        value: your_salt_value
      - key: EMAIL_SENDER
        value: your_email@example.com
      - key: EMAIL_PASSWORD
        value: your_email_password
      - key: SMTP_SERVER
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
